name: Notifications Disabled (for ease of open source contributions)

on:
  push:
      branches:
        - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - run: |
          found=($(grep "^apply plugin: 'com.google.gms.google-services'" android/app/build.gradle | wc -l))
          [ "$found" == "0" ] || exit 1
          exit 0
